// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyVinCafeNewLibrary.Data;

#nullable disable

namespace MyVinCafeNewLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415062632_TambahFitur")]
    partial class TambahFitur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyVinCafeNewLibrary.Feature.AlatKafeManagement.AlatCafeModel", b =>
                {
                    b.Property<int>("IdAlat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlat"));

                    b.Property<decimal>("HargaAlat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("JumlahAlat")
                        .HasColumnType("int");

                    b.Property<string>("NamaAlat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAlat");

                    b.ToTable("Alats");
                });

            modelBuilder.Entity("MyVinCafeNewLibrary.Feature.MenuProdukManagement.MenuModels", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenu"));

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("GambarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaMenu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMenu");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("MyVinCafeNewLibrary.Feature.OrderManagement.OrderModel", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<int>("IdMenu")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int?>("MenuModelsIdMenu")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalOrder")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalHarga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserModelIduser")
                        .HasColumnType("int");

                    b.HasKey("IdOrder");

                    b.HasIndex("MenuModelsIdMenu");

                    b.HasIndex("UserModelIduser");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MyVinCafeNewLibrary.Feature.UserManagement.AuthModel", b =>
                {
                    b.Property<int>("Iduser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iduser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Iduser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyVinCafeNewLibrary.Feature.UserManagement.KaryawanModel", b =>
                {
                    b.Property<int>("IdKaryawan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKaryawan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKaryawan");

                    b.ToTable("Karyawans");
                });

            modelBuilder.Entity("MyVinCafeNewLibrary.Feature.OrderManagement.OrderModel", b =>
                {
                    b.HasOne("MyVinCafeNewLibrary.Feature.MenuProdukManagement.MenuModels", "MenuModels")
                        .WithMany()
                        .HasForeignKey("MenuModelsIdMenu");

                    b.HasOne("MyVinCafeNewLibrary.Feature.UserManagement.AuthModel", "UserModel")
                        .WithMany()
                        .HasForeignKey("UserModelIduser");

                    b.Navigation("MenuModels");

                    b.Navigation("UserModel");
                });
#pragma warning restore 612, 618
        }
    }
}
